kind: pipeline
name: axentix new release

steps:
- name: send
  image: plugins/webhook
  secrets: [ hook_headers ]
  settings:
    urls: https://dev.useaxentix.com/api/hook
    content_type: application/json
    headers: "${HOOK_HEADERS}"
    template: |
      {
        "version": "{{ build.tag }}",
      }
    debug: true
  when:
    event:
      - tag