kind: pipeline
name: axentix new release

steps:
- name: send
  image: plugins/webhook
  settings:
    urls: https://dev.useaxentix.com/api/hook
    template: |
      {
        "version": "{{ build.tag }}"
      }
    debug: true
  when:
    event:
      - tag
      