kind: pipeline
name: axentix new release

steps:
- name: send
  image: plugins/webhook
  settings:
    urls: https://dev.useaxentix.com/api/hook
    headers:
      from_secret: hook_headers
    template: |
      {
        "version": "{{ build.tag }}"
      }
  when:
    event:
      - tag