kind: pipeline
name: axentix new release

steps:
- name: send
  image: plugins/webhook
  settings:
    urls: https://dev.useaxentix.com/api/hook
    content_type: application/json
    template: |
      {
        "version": "{{ build.tag }}",
      }
  when:
    event:
      - tag